/*
    "scripts": [
      "/lib/polyfill.js",
      "/lib/checkedLastError.js",
      "/lib/stuff.js",
      "/lib/languages.js",
      "/lib/config.js",
      "/lib/platformInfo.js",
      "/lib/i18n.js",
      "/background/translationCache.js",
      "/background/translationService.js",
      "/background/textToSpeech.js",
      "/background/background.js"
    ]
*/


importScripts('/lib/XMLHttpRequestShim.js');
importScripts("/lib/polyfill.js");
importScripts("/lib/checkedLastError.js");
importScripts("/lib/stuff.js");
importScripts("/lib/languages.js");
importScripts("/lib/config.js");
importScripts("/lib/platformInfo.js");
importScripts("/lib/i18n.js");
importScripts("/background/translationCache.js");
importScripts("/background/aiService.bundle.js");
importScripts("/background/translationService.js");
importScripts("/background/offlineDictionary.js");
importScripts("/background/dictionary.js");
importScripts("/background/sidePanel.js");
importScripts("/background/imageCapture.js");
importScripts("/lib/videoSubtitles.js");
importScripts("/background/videoSubtitles.js");
importScripts("/lib/youtubeSubtitles.js");
importScripts("/background/youtubeSubtitles.js");
importScripts("/background/localVoice.js");
importScripts("/background/textToSpeech.js");
importScripts("/background/background.js");
